sudo: required
services: docker
branches:
  except: /^\d+$/
script: |
  export TRAVIS_TAG=$(( $(git tag --list --sort=creatordate | tail -n1) + 1 ))
  docker build . -t "$TRAVIS_REPO_SLUG:$TRAVIS_TAG"
before_deploy:
- docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD"
- docker tag "$TRAVIS_REPO_SLUG:$TRAVIS_TAG" "$TRAVIS_REPO_SLUG:latest"
- git config --local user.name "bot50"
- git config --local user.email "bot@cs50.harvard.edu"
deploy:
- provider: script
  script: docker push "$TRAVIS_REPO_SLUG:$TRAVIS_TAG" && docker push "$TRAVIS_REPO_SLUG:latest"
  on:
    branch: master
- provider: releases
  api_key: $GITHUB_TOKEN
  skip_cleanup: true
  on:
    branch: master
after_deploy: |
  rdepends="check server"
  for r in rdepends; do
    curl -s -X POST \
      -H "Content-Type: application/json" \
      -H "Accept: application/json" \
      -H "Travis-API-Version: 3" \
      -H "Authorization: token $TRAVIS_TOKEN" \
      -d '{"request": {"branch": "master"}}' \
      "https://api.travis-ci.com/repo/$ORG%2F$REPO/requests"
  done
notifications:
  slack:
    secure: TdG2YcICS9VU6oUmWHNm69l1ZzXi3fcL+9iGlWBjtSZW0UKu3KB4lpV4coVJntegJvt/WgeNUS7iU6KtuEoWATGD3ts6kwI3tNkZaDlpn9Ad6tRWFem3aNz0fVl33It6ZcuDmcXKIvcSiywVUKEDEvIvoByih4kovSDWNAwUbn24DeodI/UyKmigguFv23wYFHRj5VbbRqiE4hR0OrPuRCKYm6Yl53mM7apB9ZuydYjI3ANPPNOr8YBX5JF8Cwp5e8Kq2yHNZ6G1PeB3R/umpgQB6GJ60Vx7tNBg8Ce8YFT5t6w4EFqgqObSw/UeO5Z9q+UhCV4PPuVuqme49ULMNFkLxUy6QBzvj87Xh5s7P4seVC6q29uGnAvhq1AF13CQdUHyWXjzH3PNH5gpmpj0JBFH6R4azHAvwNDj/5tDI4CyzS9iVMoBLHdVqHCev1CqNwfv0hc+IdCrw2iJdq55Yacb5cB/ONN3c9MtbhvRIVa0om7VZqf70mHXLyfhXuHzB+3OKS5CMTI466bv0XzEmrw61nxeCAd9o4iN9TW6+4okfJ657J/Lbil1xNB6up3E0UiUFQt/YLLXRp6Xlo7pUFOmb+3K6CGfKVA/iGZCdBLwkRQJ1dRIUjbZjNProRkjPfuZkl2bkVdy4y0dIHi0wJwxUI4KM/QOF3vFJcia0iY=
